[versions]
agp = "8.13.2"
kotlin = "2.3.21"
junit = "4.13.2"
orgJson = "20260814"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
org-json = { module = "org.json:json", version.ref = "orgJson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
