package se.sensnology.spotnav.ha.dashboard

/**
 * The words of the status line, one table per locale, taken from the Home Assistant card's own
 * translations (`frontend/src/i18n`) so the app says the same thing in the same words.
 */
internal object HaStatusWording {
    /** The sentence each Home Assistant status code is worded with (`status.ts`' `STATUS_WORDING`). */
    val CODE_KEYS: Map<String, String> = mapOf(
        "charger_unavailable" to "issue.chargerMissing",
        "price_data_invalid" to "issue.priceInvalid",
        "price_data_unavailable" to "issue.priceUnavailable",
        "settings_incomplete" to "issue.incompleteSettings",
        "settings_suggested" to "status.settingsSuggested",
        "solar_unavailable" to "issue.solarUnavailable",
        "target_soc_unknown" to "issue.targetSocUnknown",
        "price_horizon_missing" to "issue.priceHorizon",
        "planning_unavailable" to "issue.planningUnavailable",
        "planning_error" to "issue.error",
        "paused" to "control.pausedUntil",
        "charging_now" to "status.chargingNow",
        "charging_without_prices" to "issue.chargingWithoutPrices",
        "waiting_for_publication" to "status.waitingForPublication",
        "buying_before_publication" to "status.buyingBeforePublication",
        "auto_planned" to "status.autoPlanned",
        "auto_installed" to "status.autoInstalled",
        "proposal_pending" to "status.proposalPending",
        "waiting_for_tomorrow" to "status.waitingForTomorrow",
        "no_plan" to "status.noPlan",
        "nothing_to_charge" to "status.nothingToCharge",
        "plan_energy" to "status.planEnergy",
        "plan_cost" to "status.planCost",
        "plan_distance" to "status.planDistance",
        "solar_charging" to "strategy.status.solar.charging",
        "solar_arming" to "strategy.status.solar.arming",
        "solar_disarming" to "strategy.status.solar.disarming",
        "solar_no_reading_stopped" to "strategy.status.solar.noReadingStopped",
        "solar_no_reading_waiting" to "strategy.status.solar.noReadingWaiting",
        "solar_waiting_for_sun" to "strategy.status.solar.waitingForSun",
        "solar_vehicle_full" to "strategy.status.solar.vehicleFull",
        "solar_car_stopped" to "strategy.status.solar.carStopped",
        "solar_unknown" to "strategy.status.solar.unknown",
        "hybrid_grid" to "strategy.status.hybrid.grid",
        "hybrid_no_forecast" to "strategy.status.hybrid.noForecast",
        "hybrid_no_price_data" to "strategy.status.hybrid.noPriceData",
        "hybrid_satisfied" to "strategy.status.hybrid.satisfied",
        "hybrid_unknown" to "strategy.status.hybrid.unknown",
        "target_reached" to "status.targetStopped",
        "target_unverifiable" to "issue.targetUnverifiable",
        "price_data_stale" to "issue.priceStale",
        "price_data_degraded" to "issue.priceDegraded",
        "unpriced" to "issue.estimated",
        "load_balancing_limited" to "status.loadBalancingLimitedTo",
        "load_balancing_unavailable" to "issue.loadBalancing",
        "waiting_for_history" to "status.waitingForHistory",
        "held_by_charger" to "issue.heldByCharger",
        "charger_disabled" to "issue.chargerDisabled",
        "held_until_window" to "status.heldUntilWindow",
        "hold_overridden" to "issue.holdOverridden",
        "stopped_by_person" to "status.stoppedByPerson",
        "site_measurement_problem" to "issue.siteMeasurement",
        "duplicate_charger" to "issue.duplicateCharger",
        "starting_up" to "status.startingUp",
        "remaining_need_estimated" to "issue.needKept",
        "need_limited_by_room" to "status.needLimitedByRoom",
        "charging_to_vehicle_limit" to "status.chargingToVehicleLimit",
        "topping_off" to "status.toppingOff",
        "solar_no_grid_power" to "strategy.status.solar.noGridPower",
        "solar_battery_unreadable" to "strategy.status.solar.batteryUnreadable",
        "solar_charger_current_missing" to "strategy.status.solar.chargerCurrentNotSet",
        "solar_site_incomplete" to "strategy.status.solar.siteIncomplete",
        "site_meter_unavailable" to "status.meterUnavailable.meter",
    )

    /** The extra keys a code's variants use (an absent fact, or no zone to write an instant in). */
    val VARIANT_KEYS: List<String> = listOf(
        "status.finishSetupArea",
        "status.finishSetup",
        "status.missing.area",
        "status.missing.phases",
        "status.missing.amps",
        "status.missing.vehicle",
        "status.missing.target_percent",
        "control.pausedIndefinitely",
        "status.pausedShort",
        "status.targetStoppedAge",
        "status.targetStoppedNow",
        "status.targetStoppedEstimate",
        "status.targetStoppedEstimateAge",
        "status.targetAgeMinutes",
        "status.targetAgeHours",
        "status.chargingNowOpen",
        "status.toppingOffOpen",
        "status.scheduledNoTime",
        "status.waitingForPublicationNoTime",
        "status.loadBalancingLimited",
        "status.loadBalancingLimitedByBattery",
        "status.loadBalancingLimitedByHouse",
        "status.proposalPendingAt",
        "status.waitingForHistoryNoDetail",
        "strategy.status.solar.chargingUnknown",
        "strategy.status.hybrid.creditSuffix",
        "status.siteMeasurement.noValue.one",
        "status.siteMeasurement.noValue.other",
        "status.siteMeasurement.stale.one",
        "status.siteMeasurement.stale.other",
        "issue.needFromSessions",
        "strategy.status.solar.noGridPowerEntity",
        "strategy.status.solar.chargerCurrentUnreadable",
        "status.meterUnavailable.inverter",
        "status.stoppedByPersonUntilStart",
        "strategy.status.solar.carStoppedNoTime",
    )

    /** The app's own additions: a status this app version cannot word, and the age of a kept one. */
    const val UNKNOWN_CODE = "app.status.unknown"
    const val STALE_SUFFIX = "app.status.staleSuffix"

    private val APP_ONLY: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(UNKNOWN_CODE to "Charging status: see Home Assistant.", STALE_SUFFIX to "updated {age} ago"),
        "sv" to mapOf(UNKNOWN_CODE to "Laddstatus: se Home Assistant.", STALE_SUFFIX to "uppdaterad för {age} sedan"),
        "da" to mapOf(UNKNOWN_CODE to "Ladestatus: se Home Assistant.", STALE_SUFFIX to "opdateret for {age} siden"),
        "nb" to mapOf(UNKNOWN_CODE to "Ladestatus: se Home Assistant.", STALE_SUFFIX to "oppdatert for {age} siden"),
        "fi" to mapOf(UNKNOWN_CODE to "Latauksen tila: katso Home Assistant.", STALE_SUFFIX to "päivitetty {age} sitten"),
    )

    private val CARD: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "status.proposalPendingAt" to "A new plan is ready and is installed when the current charging window ends at {time}.",
            "status.loadBalancingLimitedByBattery" to "The home battery charges from the grid and shares the main fuse: the car gets {limit} A.",
            "status.loadBalancingLimitedByHouse" to "House consumption limits the car to {limit} A.",
            "control.pausedIndefinitely" to "Paused until you resume.",
            "status.heldUntilWindow" to "Charging waits for the planned start at {time}.",
            "status.waitingForHistory" to "Waiting: {weekday} were {percent} % cheaper the last {weeks} weeks.",
            "status.waitingForHistoryNoDetail" to "Waiting for hours that usually cost less, will plan then.",
            "issue.heldByCharger" to "The charger's own schedule or load balancing is holding the charge, so it has not started.",
            "issue.chargerDisabled" to "The charger's own enable switch is off, so it cannot start. Turn it on in the charger's settings.",
            "issue.holdOverridden" to "Charging was started outside the plan and is allowed to continue.",
            "status.stoppedByPerson" to "You stopped the charge. The sun does not start it again until the car is plugged in again, you press Start now or a planned window begins.",
            "status.stoppedByPersonUntilStart" to "You stopped the charge. The sun does not start it again until you press Start now or the next planned window begins.",
            "status.siteMeasurement.stale.other" to "{phases} are older than {seconds} s.",
            "status.siteMeasurement.stale.one" to "{phases} is older than {seconds} s.",
            "status.siteMeasurement.noValue.other" to "{phases} have no value{where}.",
            "status.siteMeasurement.noValue.one" to "{phases} has no value{where}.",
            "issue.duplicateCharger" to "{other} and this charger are the same physical charger. Two SpotNav chargers on one charger send it conflicting commands, so keep only one: remove the other in Settings → Devices & services → SpotNav. SpotNav never removes one for you.",
            "status.startingUp" to "Starting up…",
            "issue.needKept" to "The energy meter cannot be read: {kwh} kWh remains, from its last reading.",
            "issue.needFromSessions" to "No energy meter: {kwh} kWh remains, counted from this charger's recorded charges.",
            "status.needLimitedByRoom" to "Limited to {kwh} kWh: the car is almost full.",
            "status.chargingToVehicleLimit" to "Charging until the car stops at its own limit ({percent} %).",
            "issue.siteMeasurement" to "The site's measurement cannot be used right now.",
            "control.pausedUntil" to "Paused until {time}.",
            "issue.chargerMissing" to "The configured charger is not usable: it is unknown, unloaded or a site.",
            "issue.chargingWithoutPrices" to "Charging without published prices to keep the deadline.",
            "issue.error" to "The last calculation failed.",
            "issue.estimated" to "Part of the plan charges without published prices.",
            "issue.incompleteSettings" to "Finish setting up: some settings are still missing. Open Settings.",
            "issue.loadBalancing" to "Load balancing is not available for this charger.",
            "issue.planningUnavailable" to "No charging plan could be calculated with the data available right now.",
            "issue.priceDegraded" to "The price data is incomplete.",
            "issue.priceHorizon" to "Prices are missing for part of the required planning window. Set a deadline.",
            "issue.priceInvalid" to "The price data is invalid.",
            "issue.priceStale" to "The prices are stale: the last successful fetch is still being used.",
            "issue.priceUnavailable" to "No usable price data is available right now.",
            "issue.solarUnavailable" to "Solar charging is not available: this site cannot measure solar surplus.",
            "issue.targetSocUnknown" to "The target charge level cannot be planned: the vehicle's charge level or battery capacity is not known. Open Plan to choose a sensor or enter the capacity.",
            "issue.targetUnverifiable" to "The target can't be checked right now.",
            "status.autoInstalled" to "Charging is scheduled from {time}.",
            "status.autoPlanned" to "Planned from {time}.",
            "status.buyingBeforePublication" to "Buying {kwh} kWh now, the rest when the prices are published.",
            "status.chargingNow" to "Charging now; scheduled until {time}.",
            "status.chargingNowOpen" to "Charging now.",
            "status.toppingOff" to "Charging until the car is full (at most until {time}).",
            "status.toppingOffOpen" to "Charging until the car is full.",
            "status.loadBalancingLimited" to "Charging is limited by the site's load balancing right now.",
            "status.loadBalancingLimitedTo" to "Charging is limited to {limit} A by the site's load balancing.",
            "status.noPlan" to "No charging plan could be calculated right now.",
            "status.nothingToCharge" to "Nothing to charge right now.",
            "status.pausedShort" to "Automatic charging is paused.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "A new charging proposal is ready.",
            "status.scheduledNoTime" to "Charging is scheduled.",
            "status.targetAgeHours" to "{n} h",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Stopped at {soc} %",
            "status.targetStoppedAge" to "Stopped at {soc} % (reading {age} old)",
            "status.targetStoppedEstimate" to "Stopped at {soc} % (estimated)",
            "status.targetStoppedEstimateAge" to "Stopped at {soc} % (estimated, reading {age} old)",
            "status.targetStoppedNow" to "Stopped at {soc} % (just now)",
            "status.waitingForPublication" to "Waiting for tomorrow's prices (~{time}), will plan then.",
            "status.waitingForPublicationNoTime" to "Waiting for tomorrow's prices, will plan then.",
            "status.waitingForTomorrow" to "Waiting for tomorrow's prices.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh expected from sun",
            "strategy.status.hybrid.grid" to "Hybrid · {grid} kWh from grid{window}",
            "strategy.status.hybrid.noForecast" to "Hybrid · no forecast source — planning like Cheapest",
            "strategy.status.hybrid.noPriceData" to "Hybrid · waiting for price data",
            "strategy.status.hybrid.satisfied" to "Hybrid · charging need already met",
            "strategy.status.hybrid.unknown" to "Hybrid · planning",
            "strategy.status.solar.arming" to "Solar · surplus found, starting soon",
            "strategy.status.solar.charging" to "Solar · charging {amps} A from surplus",
            "strategy.status.solar.chargingUnknown" to "Solar · charging from surplus",
            "strategy.status.solar.disarming" to "Solar · surplus fading, stopping soon",
            "strategy.status.solar.noReadingStopped" to "Solar · stopped, no usable reading",
            "strategy.status.solar.noReadingWaiting" to "Solar · no usable reading yet",
            "strategy.status.solar.unknown" to "Solar · status unknown",
            "strategy.status.solar.waitingForSun" to "Solar · waiting for sun",
            "strategy.status.solar.vehicleFull" to "Solar · the car is full",
            "strategy.status.solar.carStopped" to "Solar · the car stopped charging; trying again at {time}",
            "strategy.status.solar.carStoppedNoTime" to "Solar · the car stopped charging",
            "strategy.status.solar.noGridPower" to "Solar · no grid power reading — set Total grid power under Site entities",
            "strategy.status.solar.noGridPowerEntity" to "Solar · the total grid power ({entity}) has no fresh reading",
            "strategy.status.solar.batteryUnreadable" to "Solar · the battery power ({entity}) has no fresh reading",
            "strategy.status.solar.chargerCurrentNotSet" to "The charger's own current is not set — choose it under Site wiring (e.g. Easee Current); until then solar starts only at the minimum current.",
            "strategy.status.solar.chargerCurrentUnreadable" to "The charger's own current ({entity}) has no reading; until then solar starts only at the minimum current.",
            "strategy.status.solar.siteIncomplete" to "The site measurement is incomplete ({phases}) — solar runs on total grid power only.",
            "status.meterUnavailable.inverter" to "The meter's sensors are unavailable (the inverter may be in standby): {entities}.",
            "status.meterUnavailable.meter" to "The meter's sensors are unavailable: {entities}.",
            "status.finishSetupArea" to "Finish setting up: choose a price area in Settings.",
            "status.finishSetup" to "Finish setting up in Settings: {fields}.",
            "status.settingsSuggested" to "Suggested from your location and charger – check Settings.",
            "status.missing.area" to "price area",
            "status.missing.phases" to "phases",
            "status.missing.amps" to "charging current",
            "status.missing.vehicle" to "vehicle",
            "status.missing.target_percent" to "target level",
        ),
        "sv" to mapOf(
            "status.proposalPendingAt" to "En ny plan väntar och installeras när pågående laddfönster slutar kl. {time}.",
            "status.loadBalancingLimitedByBattery" to "Hemmabatteriet laddar från nätet och delar huvudsäkringen: bilen får {limit} A.",
            "status.loadBalancingLimitedByHouse" to "Hushållets förbrukning begränsar bilen till {limit} A.",
            "control.pausedIndefinitely" to "Pausad tills du återupptar.",
            "status.heldUntilWindow" to "Laddningen väntar till planerad start kl. {time}.",
            "status.waitingForHistory" to "Väntar: {weekday} har varit {percent} % billigare de senaste {weeks} veckorna.",
            "status.waitingForHistoryNoDetail" to "Väntar på timmar som brukar vara billigare, planerar då.",
            "issue.heldByCharger" to "Laddarens eget schema eller lastbalansering håller tillbaka laddningen, så den har inte startat.",
            "issue.chargerDisabled" to "Laddarens egen aktiveringsbrytare är av, så den kan inte starta. Slå på den i laddarens inställningar.",
            "issue.holdOverridden" to "Laddningen startades utanför planen och får fortsätta.",
            "status.stoppedByPerson" to "Du stoppade laddningen. Solen startar den inte igen förrän bilen kopplas in på nytt, du trycker på Starta nu eller ett planerat fönster börjar.",
            "status.stoppedByPersonUntilStart" to "Du stoppade laddningen. Solen startar den inte igen förrän du trycker på Starta nu eller nästa planerade fönster börjar.",
            "status.siteMeasurement.stale.other" to "{phases} är äldre än {seconds} s.",
            "status.siteMeasurement.stale.one" to "{phases} är äldre än {seconds} s.",
            "status.siteMeasurement.noValue.other" to "{phases} saknar värde{where}.",
            "status.siteMeasurement.noValue.one" to "{phases} saknar värde{where}.",
            "issue.duplicateCharger" to "{other} och den här laddaren är samma fysiska laddare. Två SpotNav-laddare på en laddare skickar motstridiga kommandon, så behåll bara en: ta bort den andra under Inställningar → Enheter och tjänster → SpotNav. SpotNav tar aldrig bort en åt dig.",
            "status.startingUp" to "Startar upp…",
            "issue.needKept" to "Energimätaren kan inte läsas: {kwh} kWh återstår enligt dess senaste värde.",
            "issue.needFromSessions" to "Ingen energimätare: {kwh} kWh återstår, räknat från laddarens sparade laddningar.",
            "status.needLimitedByRoom" to "Begränsat till {kwh} kWh: bilen är nästan full.",
            "status.chargingToVehicleLimit" to "Laddar tills bilen stoppar vid sin egen laddgräns ({percent} %).",
            "issue.siteMeasurement" to "Anläggningens mätning kan inte användas just nu.",
            "control.pausedUntil" to "Pausad till {time}.",
            "issue.chargerMissing" to "Den valda laddaren går inte att använda: den är okänd, inte laddad eller en anläggning.",
            "issue.chargingWithoutPrices" to "Laddar utan publicerade priser för att hålla sluttiden.",
            "issue.error" to "Den senaste beräkningen misslyckades.",
            "issue.estimated" to "En del av planen laddar utan publicerade priser.",
            "issue.incompleteSettings" to "Slutför inställningen: några inställningar saknas fortfarande. Öppna Inställningar.",
            "issue.loadBalancing" to "Lastbalansering är inte tillgänglig för den här laddaren.",
            "issue.planningUnavailable" to "Ingen laddplan kunde beräknas med de uppgifter som finns just nu.",
            "issue.priceDegraded" to "Prisunderlaget är ofullständigt.",
            "issue.priceHorizon" to "Priser saknas för en del av planeringsperioden. Ange en avresetid.",
            "issue.priceInvalid" to "Prisuppgifterna är ogiltiga.",
            "issue.priceStale" to "Priserna är inaktuella: den senaste lyckade hämtningen används fortfarande.",
            "issue.priceUnavailable" to "Inga användbara prisuppgifter finns just nu.",
            "issue.solarUnavailable" to "Solladdning är inte tillgänglig: anläggningen kan inte mäta solöverskott.",
            "issue.targetSocUnknown" to "Målnivån kan inte planeras: fordonets laddnivå eller batterikapacitet är okänd. Öppna Plan för att välja sensor eller ange kapaciteten.",
            "issue.targetUnverifiable" to "Målet kan inte kontrolleras just nu.",
            "status.autoInstalled" to "Laddning är schemalagd från {time}.",
            "status.autoPlanned" to "Planerat från {time}.",
            "status.buyingBeforePublication" to "Köper {kwh} kWh nu, resten när priserna publiceras.",
            "status.chargingNow" to "Laddar nu; schemalagd till {time}.",
            "status.chargingNowOpen" to "Laddar nu.",
            "status.toppingOff" to "Laddar tills bilen är full (som längst till {time}).",
            "status.toppingOffOpen" to "Laddar tills bilen är full.",
            "status.loadBalancingLimited" to "Laddningen begränsas av anläggningens lastbalansering just nu.",
            "status.loadBalancingLimitedTo" to "Laddningen begränsas till {limit} A av anläggningens lastbalansering.",
            "status.noPlan" to "Ingen laddplan kunde beräknas just nu.",
            "status.nothingToCharge" to "Inget att ladda just nu.",
            "status.pausedShort" to "Automatisk laddning är pausad.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "Ett nytt laddförslag är klart.",
            "status.scheduledNoTime" to "Laddning är schemalagd.",
            "status.targetAgeHours" to "{n} h",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Stoppad vid {soc} %",
            "status.targetStoppedAge" to "Stoppad vid {soc} % (avläsningen {age} gammal)",
            "status.targetStoppedEstimate" to "Stoppad vid {soc} % (uppskattat)",
            "status.targetStoppedEstimateAge" to "Stoppad vid {soc} % (uppskattat, avläsningen {age} gammal)",
            "status.targetStoppedNow" to "Stoppad vid {soc} % (nyss)",
            "status.waitingForPublication" to "Väntar på morgondagens priser (~{time}), planerar då.",
            "status.waitingForPublicationNoTime" to "Väntar på morgondagens priser, planerar då.",
            "status.waitingForTomorrow" to "Väntar på morgondagens priser.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh väntas från solen",
            "strategy.status.hybrid.grid" to "Hybrid · {grid} kWh från elnätet{window}",
            "strategy.status.hybrid.noForecast" to "Hybrid · ingen prognoskälla — planerar som Billigast",
            "strategy.status.hybrid.noPriceData" to "Hybrid · väntar på prisuppgifter",
            "strategy.status.hybrid.satisfied" to "Hybrid · laddbehovet är redan uppfyllt",
            "strategy.status.hybrid.unknown" to "Hybrid · planerar",
            "strategy.status.solar.arming" to "Sol · överskott hittat, startar snart",
            "strategy.status.solar.charging" to "Sol · laddar med {amps} A från överskott",
            "strategy.status.solar.chargingUnknown" to "Sol · laddar från överskott",
            "strategy.status.solar.disarming" to "Sol · överskottet minskar, stoppar snart",
            "strategy.status.solar.noReadingStopped" to "Sol · stoppad, ingen användbar mätning",
            "strategy.status.solar.noReadingWaiting" to "Sol · ingen användbar mätning ännu",
            "strategy.status.solar.unknown" to "Sol · status okänd",
            "strategy.status.solar.waitingForSun" to "Sol · väntar på sol",
            "strategy.status.solar.vehicleFull" to "Sol · bilen är fulladdad",
            "strategy.status.solar.carStopped" to "Sol · bilen slutade ladda; försöker igen kl. {time}",
            "strategy.status.solar.carStoppedNoTime" to "Sol · bilen slutade ladda",
            "strategy.status.solar.noGridPower" to "Sol · ingen mätning av nätets effekt — ange Nätets totala effekt under Anläggningens entiteter",
            "strategy.status.solar.noGridPowerEntity" to "Sol · nätets totala effekt ({entity}) har ingen färsk mätning",
            "strategy.status.solar.batteryUnreadable" to "Sol · batteriets effekt ({entity}) har ingen färsk mätning",
            "strategy.status.solar.chargerCurrentNotSet" to "Laddarens egen ström är inte vald — välj den under Anläggningens koppling (t.ex. Easee Current); till dess startar sol bara på minsta ström.",
            "strategy.status.solar.chargerCurrentUnreadable" to "Laddarens egen ström ({entity}) har ingen mätning; till dess startar sol bara på minsta ström.",
            "strategy.status.solar.siteIncomplete" to "Anläggningens mätning är ofullständig ({phases}) — sol går bara på nätets totala effekt.",
            "status.meterUnavailable.inverter" to "Mätarens sensorer är otillgängliga (växelriktaren kan vara i viloläge): {entities}.",
            "status.meterUnavailable.meter" to "Mätarens sensorer är otillgängliga: {entities}.",
            "status.finishSetupArea" to "Slutför inställningen: välj ett prisområde i Inställningar.",
            "status.finishSetup" to "Slutför inställningen i Inställningar: {fields}.",
            "status.settingsSuggested" to "Förslag utifrån din plats och laddare – kontrollera Inställningar.",
            "status.missing.area" to "prisområde",
            "status.missing.phases" to "faser",
            "status.missing.amps" to "laddström",
            "status.missing.vehicle" to "fordon",
            "status.missing.target_percent" to "målnivå",
        ),
        "da" to mapOf(
            "status.proposalPendingAt" to "En ny plan er klar og installeres, når det igangværende opladningsvindue slutter kl. {time}.",
            "status.loadBalancingLimitedByBattery" to "Hjemmebatteriet oplader fra nettet og deler hovedsikringen: bilen får {limit} A.",
            "status.loadBalancingLimitedByHouse" to "Husets forbrug begrænser bilen til {limit} A.",
            "control.pausedIndefinitely" to "Sat på pause, indtil du genoptager.",
            "status.heldUntilWindow" to "Opladningen venter til den planlagte start kl. {time}.",
            "status.waitingForHistory" to "Venter: {weekday} har været {percent} % billigere de seneste {weeks} uger.",
            "status.waitingForHistoryNoDetail" to "Venter på timer, der plejer at være billigere, planlægger derefter.",
            "issue.heldByCharger" to "Laderens eget skema eller lastbalancering holder opladningen tilbage, så den er ikke startet.",
            "issue.chargerDisabled" to "Laderens egen aktiveringskontakt er slået fra, så den kan ikke starte. Slå den til i laderens indstillinger.",
            "issue.holdOverridden" to "Opladningen blev startet uden for planen og må fortsætte.",
            "status.stoppedByPerson" to "Du stoppede opladningen. Solen starter den ikke igen, før bilen tilsluttes på ny, du trykker på Start nu, eller et planlagt vindue begynder.",
            "status.stoppedByPersonUntilStart" to "Du stoppede opladningen. Solen starter den ikke igen, før du trykker på Start nu, eller det næste planlagte vindue begynder.",
            "status.siteMeasurement.stale.other" to "{phases} er ældre end {seconds} s.",
            "status.siteMeasurement.stale.one" to "{phases} er ældre end {seconds} s.",
            "status.siteMeasurement.noValue.other" to "{phases} har ingen værdi{where}.",
            "status.siteMeasurement.noValue.one" to "{phases} har ingen værdi{where}.",
            "issue.duplicateCharger" to "{other} og denne lader er den samme fysiske lader. To SpotNav-ladere på én lader sender modstridende kommandoer, så behold kun én: fjern den anden under Indstillinger → Enheder og tjenester → SpotNav. SpotNav fjerner aldrig en for dig.",
            "status.startingUp" to "Starter op…",
            "issue.needKept" to "Energimåleren kan ikke aflæses: {kwh} kWh mangler ifølge seneste aflæsning.",
            "issue.needFromSessions" to "Ingen energimåler: {kwh} kWh mangler, regnet ud fra laderens gemte opladninger.",
            "status.needLimitedByRoom" to "Begrænset til {kwh} kWh: bilen er næsten fuld.",
            "status.chargingToVehicleLimit" to "Lader, indtil bilen stopper ved sin egen ladegrænse ({percent} %).",
            "issue.siteMeasurement" to "Anlæggets måling kan ikke bruges lige nu.",
            "control.pausedUntil" to "Sat på pause til {time}.",
            "issue.chargerMissing" to "Den valgte lader kan ikke bruges: den er ukendt, ikke indlæst eller et anlæg.",
            "issue.chargingWithoutPrices" to "Lader uden offentliggjorte priser for at overholde sluttidspunktet.",
            "issue.error" to "Den seneste beregning mislykkedes.",
            "issue.estimated" to "En del af planen lader uden offentliggjorte priser.",
            "issue.incompleteSettings" to "Færdiggør opsætningen: nogle indstillinger mangler stadig. Åbn Indstillinger.",
            "issue.loadBalancing" to "Lastbalancering er ikke tilgængelig for denne lader.",
            "issue.planningUnavailable" to "Der kunne ikke beregnes en ladeplan med de data, der er tilgængelige lige nu.",
            "issue.priceDegraded" to "Prisdata er ufuldstændige.",
            "issue.priceHorizon" to "Priser mangler for en del af planlægningsvinduet. Angiv et afrejsetidspunkt.",
            "issue.priceInvalid" to "Prisdataene er ugyldige.",
            "issue.priceStale" to "Priserne er forældede: den seneste vellykkede hentning bruges stadig.",
            "issue.priceUnavailable" to "Der er ingen brugbare prisdata lige nu.",
            "issue.solarUnavailable" to "Soloplading er ikke tilgængelig: dette anlæg kan ikke måle soloverskud.",
            "issue.targetSocUnknown" to "Ladetilstandsmålet kan ikke planlægges: bilens ladetilstand eller batterikapacitet er ukendt. Åbn Plan for at vælge en sensor eller angive kapaciteten.",
            "issue.targetUnverifiable" to "Målet kan ikke kontrolleres lige nu.",
            "status.autoInstalled" to "Opladning er planlagt fra {time}.",
            "status.autoPlanned" to "Planlagt fra {time}.",
            "status.buyingBeforePublication" to "Køber {kwh} kWh nu, resten når priserne er offentliggjort.",
            "status.chargingNow" to "Lader nu; planlagt til {time}.",
            "status.chargingNowOpen" to "Lader nu.",
            "status.toppingOff" to "Lader, indtil bilen er fuld (højst til {time}).",
            "status.toppingOffOpen" to "Lader, indtil bilen er fuld.",
            "status.loadBalancingLimited" to "Opladningen begrænses af anlæggets lastbalancering lige nu.",
            "status.loadBalancingLimitedTo" to "Opladningen begrænses til {limit} A af anlæggets lastbalancering.",
            "status.noPlan" to "Der kunne ikke beregnes en ladeplan lige nu.",
            "status.nothingToCharge" to "Der er intet at lade lige nu.",
            "status.pausedShort" to "Automatisk opladning er sat på pause.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "Et nyt opladningsforslag er klar.",
            "status.scheduledNoTime" to "Opladning er planlagt.",
            "status.targetAgeHours" to "{n} t",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Stoppet ved {soc} %",
            "status.targetStoppedAge" to "Stoppet ved {soc} % (aflæsningen er {age} gammel)",
            "status.targetStoppedEstimate" to "Stoppet ved {soc} % (anslået)",
            "status.targetStoppedEstimateAge" to "Stoppet ved {soc} % (anslået, aflæsningen er {age} gammel)",
            "status.targetStoppedNow" to "Stoppet ved {soc} % (lige nu)",
            "status.waitingForPublication" to "Venter på morgendagens priser (~{time}), planlægger derefter.",
            "status.waitingForPublicationNoTime" to "Venter på morgendagens priser, planlægger derefter.",
            "status.waitingForTomorrow" to "Venter på morgendagens priser.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh forventes fra solen",
            "strategy.status.hybrid.grid" to "Hybrid · {grid} kWh fra elnettet{window}",
            "strategy.status.hybrid.noForecast" to "Hybrid · ingen prognosekilde — planlægger som Billigst",
            "strategy.status.hybrid.noPriceData" to "Hybrid · venter på prisdata",
            "strategy.status.hybrid.satisfied" to "Hybrid · ladebehovet er allerede opfyldt",
            "strategy.status.hybrid.unknown" to "Hybrid · planlægger",
            "strategy.status.solar.arming" to "Sol · overskud fundet, starter snart",
            "strategy.status.solar.charging" to "Sol · lader med {amps} A fra overskud",
            "strategy.status.solar.chargingUnknown" to "Sol · lader fra overskud",
            "strategy.status.solar.disarming" to "Sol · overskuddet aftager, stopper snart",
            "strategy.status.solar.noReadingStopped" to "Sol · stoppet, ingen brugbar måling",
            "strategy.status.solar.noReadingWaiting" to "Sol · ingen brugbar måling endnu",
            "strategy.status.solar.unknown" to "Sol · status ukendt",
            "strategy.status.solar.waitingForSun" to "Sol · venter på sol",
            "strategy.status.solar.vehicleFull" to "Sol · bilen er fuldt opladet",
            "strategy.status.solar.carStopped" to "Sol · bilen stoppede opladningen; prøver igen kl. {time}",
            "strategy.status.solar.carStoppedNoTime" to "Sol · bilen stoppede opladningen",
            "strategy.status.solar.noGridPower" to "Sol · ingen måling af nettets effekt — angiv Nettets samlede effekt under Anlæggets entiteter",
            "strategy.status.solar.noGridPowerEntity" to "Sol · nettets samlede effekt ({entity}) har ingen frisk måling",
            "strategy.status.solar.batteryUnreadable" to "Sol · batteriets effekt ({entity}) har ingen frisk måling",
            "strategy.status.solar.chargerCurrentNotSet" to "Laderens egen strøm er ikke valgt — vælg den under Anlæggets tilslutning (f.eks. Easee Current); indtil da starter sol kun på mindste strøm.",
            "strategy.status.solar.chargerCurrentUnreadable" to "Laderens egen strøm ({entity}) har ingen måling; indtil da starter sol kun på mindste strøm.",
            "strategy.status.solar.siteIncomplete" to "Anlæggets måling er ufuldstændig ({phases}) — sol kører kun på nettets samlede effekt.",
            "status.meterUnavailable.inverter" to "Målerens sensorer er utilgængelige (inverteren kan være i standby): {entities}.",
            "status.meterUnavailable.meter" to "Målerens sensorer er utilgængelige: {entities}.",
            "status.finishSetupArea" to "Færdiggør opsætningen: vælg et prisområde i Indstillinger.",
            "status.finishSetup" to "Færdiggør opsætningen i Indstillinger: {fields}.",
            "status.settingsSuggested" to "Foreslået ud fra din placering og lader – tjek Indstillinger.",
            "status.missing.area" to "prisområde",
            "status.missing.phases" to "faser",
            "status.missing.amps" to "ladestrøm",
            "status.missing.vehicle" to "køretøj",
            "status.missing.target_percent" to "målniveau",
        ),
        "nb" to mapOf(
            "status.proposalPendingAt" to "En ny plan er klar og installeres når det pågående ladevinduet slutter kl. {time}.",
            "status.loadBalancingLimitedByBattery" to "Hjemmebatteriet lader fra nettet og deler hovedsikringen: bilen får {limit} A.",
            "status.loadBalancingLimitedByHouse" to "Husets forbruk begrenser bilen til {limit} A.",
            "control.pausedIndefinitely" to "Pauset til du gjenopptar.",
            "status.heldUntilWindow" to "Ladingen venter til planlagt start kl. {time}.",
            "status.waitingForHistory" to "Venter: {weekday} har vært {percent} % billigere de siste {weeks} ukene.",
            "status.waitingForHistoryNoDetail" to "Venter på timer som pleier å være billigere, planlegger da.",
            "issue.heldByCharger" to "Laderens egen timeplan eller lastbalansering holder tilbake ladingen, så den har ikke startet.",
            "issue.chargerDisabled" to "Laderens egen aktiveringsbryter er av, så den kan ikke starte. Slå den på i laderens innstillinger.",
            "issue.holdOverridden" to "Ladingen ble startet utenfor planen og får fortsette.",
            "status.stoppedByPerson" to "Du stoppet ladingen. Solen starter den ikke igjen før bilen kobles til på nytt, du trykker på Start nå eller et planlagt vindu begynner.",
            "status.stoppedByPersonUntilStart" to "Du stoppet ladingen. Solen starter den ikke igjen før du trykker på Start nå eller neste planlagte vindu begynner.",
            "status.siteMeasurement.stale.other" to "{phases} er eldre enn {seconds} s.",
            "status.siteMeasurement.stale.one" to "{phases} er eldre enn {seconds} s.",
            "status.siteMeasurement.noValue.other" to "{phases} har ingen verdi{where}.",
            "status.siteMeasurement.noValue.one" to "{phases} har ingen verdi{where}.",
            "issue.duplicateCharger" to "{other} og denne laderen er den samme fysiske laderen. To SpotNav-ladere på én lader sender motstridende kommandoer, så behold bare én: fjern den andre under Innstillinger → Enheter og tjenester → SpotNav. SpotNav fjerner aldri en for deg.",
            "status.startingUp" to "Starter opp…",
            "issue.needKept" to "Energimåleren kan ikke leses: {kwh} kWh gjenstår ifølge siste avlesning.",
            "issue.needFromSessions" to "Ingen energimåler: {kwh} kWh gjenstår, regnet ut fra laderens lagrede ladinger.",
            "status.needLimitedByRoom" to "Begrenset til {kwh} kWh: bilen er nesten full.",
            "status.chargingToVehicleLimit" to "Lader til bilen stopper ved sin egen ladegrense ({percent} %).",
            "issue.siteMeasurement" to "Anleggets måling kan ikke brukes akkurat nå.",
            "control.pausedUntil" to "Pauset til {time}.",
            "issue.chargerMissing" to "Den valgte laderen kan ikke brukes: den er ukjent, ikke lastet eller et anlegg.",
            "issue.chargingWithoutPrices" to "Lader uten publiserte priser for å holde sluttiden.",
            "issue.error" to "Den siste beregningen mislyktes.",
            "issue.estimated" to "En del av planen lader uten publiserte priser.",
            "issue.incompleteSettings" to "Fullfør oppsettet: noen innstillinger mangler fortsatt. Åpne Innstillinger.",
            "issue.loadBalancing" to "Lastbalansering er ikke tilgjengelig for denne laderen.",
            "issue.planningUnavailable" to "Ingen ladeplan kunne beregnes med dataene som finnes akkurat nå.",
            "issue.priceDegraded" to "Prisdataene er ufullstendige.",
            "issue.priceHorizon" to "Priser mangler for en del av planleggingsvinduet. Angi et avreisetidspunkt.",
            "issue.priceInvalid" to "Prisdataene er ugyldige.",
            "issue.priceStale" to "Prisene er utdaterte: den siste vellykkede hentingen brukes fortsatt.",
            "issue.priceUnavailable" to "Ingen brukbare prisdata finnes akkurat nå.",
            "issue.solarUnavailable" to "Sollading er ikke tilgjengelig: dette anlegget kan ikke måle soloverskudd.",
            "issue.targetSocUnknown" to "Ladenivåmålet kan ikke planlegges: bilens ladenivå eller batterikapasitet er ukjent. Åpne Plan for å velge sensor eller oppgi kapasiteten.",
            "issue.targetUnverifiable" to "Målet kan ikke kontrolleres akkurat nå.",
            "status.autoInstalled" to "Lading er planlagt fra {time}.",
            "status.autoPlanned" to "Planlagt fra {time}.",
            "status.buyingBeforePublication" to "Kjøper {kwh} kWh nå, resten når prisene er publisert.",
            "status.chargingNow" to "Lader nå; planlagt til {time}.",
            "status.chargingNowOpen" to "Lader nå.",
            "status.toppingOff" to "Lader til bilen er full (senest til {time}).",
            "status.toppingOffOpen" to "Lader til bilen er full.",
            "status.loadBalancingLimited" to "Ladingen begrenses av anleggets lastbalansering akkurat nå.",
            "status.loadBalancingLimitedTo" to "Ladingen begrenses til {limit} A av anleggets lastbalansering.",
            "status.noPlan" to "Ingen ladeplan kunne beregnes akkurat nå.",
            "status.nothingToCharge" to "Ingenting å lade akkurat nå.",
            "status.pausedShort" to "Automatisk lading er pauset.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "Et nytt ladeforslag er klart.",
            "status.scheduledNoTime" to "Lading er planlagt.",
            "status.targetAgeHours" to "{n} t",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Stoppet ved {soc} %",
            "status.targetStoppedAge" to "Stoppet ved {soc} % (avlesningen er {age} gammel)",
            "status.targetStoppedEstimate" to "Stoppet ved {soc} % (anslått)",
            "status.targetStoppedEstimateAge" to "Stoppet ved {soc} % (anslått, avlesningen er {age} gammel)",
            "status.targetStoppedNow" to "Stoppet ved {soc} % (akkurat nå)",
            "status.waitingForPublication" to "Venter på morgendagens priser (~{time}), planlegger da.",
            "status.waitingForPublicationNoTime" to "Venter på morgendagens priser, planlegger da.",
            "status.waitingForTomorrow" to "Venter på morgendagens priser.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh forventes fra solen",
            "strategy.status.hybrid.grid" to "Hybrid · {grid} kWh fra strømnettet{window}",
            "strategy.status.hybrid.noForecast" to "Hybrid · ingen prognosekilde — planlegger som Billigst",
            "strategy.status.hybrid.noPriceData" to "Hybrid · venter på prisdata",
            "strategy.status.hybrid.satisfied" to "Hybrid · ladebehovet er allerede dekket",
            "strategy.status.hybrid.unknown" to "Hybrid · planlegger",
            "strategy.status.solar.arming" to "Sol · overskudd funnet, starter snart",
            "strategy.status.solar.charging" to "Sol · lader med {amps} A fra overskudd",
            "strategy.status.solar.chargingUnknown" to "Sol · lader fra overskudd",
            "strategy.status.solar.disarming" to "Sol · overskuddet avtar, stopper snart",
            "strategy.status.solar.noReadingStopped" to "Sol · stoppet, ingen brukbar måling",
            "strategy.status.solar.noReadingWaiting" to "Sol · ingen brukbar måling ennå",
            "strategy.status.solar.unknown" to "Sol · status ukjent",
            "strategy.status.solar.waitingForSun" to "Sol · venter på sol",
            "strategy.status.solar.vehicleFull" to "Sol · bilen er fulladet",
            "strategy.status.solar.carStopped" to "Sol · bilen sluttet å lade; prøver igjen kl. {time}",
            "strategy.status.solar.carStoppedNoTime" to "Sol · bilen sluttet å lade",
            "strategy.status.solar.noGridPower" to "Sol · ingen måling av nettets effekt — angi Nettets samlede effekt under Anleggets entiteter",
            "strategy.status.solar.noGridPowerEntity" to "Sol · nettets samlede effekt ({entity}) har ingen fersk måling",
            "strategy.status.solar.batteryUnreadable" to "Sol · batteriets effekt ({entity}) har ingen fersk måling",
            "strategy.status.solar.chargerCurrentNotSet" to "Laderens egen strøm er ikke valgt — velg den under Anleggets kobling (f.eks. Easee Current); inntil da starter sol bare på minste strøm.",
            "strategy.status.solar.chargerCurrentUnreadable" to "Laderens egen strøm ({entity}) har ingen måling; inntil da starter sol bare på minste strøm.",
            "strategy.status.solar.siteIncomplete" to "Anleggets måling er ufullstendig ({phases}) — sol går bare på nettets samlede effekt.",
            "status.meterUnavailable.inverter" to "Målerens sensorer er utilgjengelige (vekselretteren kan være i hvilemodus): {entities}.",
            "status.meterUnavailable.meter" to "Målerens sensorer er utilgjengelige: {entities}.",
            "status.finishSetupArea" to "Fullfør oppsettet: velg et prisområde i Innstillinger.",
            "status.finishSetup" to "Fullfør oppsettet i Innstillinger: {fields}.",
            "status.settingsSuggested" to "Foreslått ut fra plassering og lader – sjekk Innstillinger.",
            "status.missing.area" to "prisområde",
            "status.missing.phases" to "faser",
            "status.missing.amps" to "ladestrøm",
            "status.missing.vehicle" to "kjøretøy",
            "status.missing.target_percent" to "målnivå",
        ),
        "fi" to mapOf(
            "status.proposalPendingAt" to "Uusi suunnitelma on valmis ja otetaan käyttöön, kun käynnissä oleva latausikkuna päättyy klo {time}.",
            "status.loadBalancingLimitedByBattery" to "Kotiakku lataa verkosta ja jakaa pääsulakkeen: auto saa {limit} A.",
            "status.loadBalancingLimitedByHouse" to "Talon kulutus rajoittaa auton {limit} A:iin.",
            "control.pausedIndefinitely" to "Keskeytetty, kunnes jatkat.",
            "status.heldUntilWindow" to "Lataus odottaa suunniteltua alkamisaikaa klo {time}.",
            "status.waitingForHistory" to "Odotetaan: {weekday} on ollut {percent} % halvempaa viimeisten {weeks} viikon aikana.",
            "status.waitingForHistoryNoDetail" to "Odotetaan tunteja, jotka ovat yleensä halvempia, suunnitellaan sen jälkeen.",
            "issue.heldByCharger" to "Laturin oma aikataulu tai kuormanhallinta pidättää latausta, joten se ei ole alkanut.",
            "issue.chargerDisabled" to "Laturin oma käyttöönottokytkin on pois päältä, joten lataus ei voi alkaa. Kytke se päälle laturin asetuksista.",
            "issue.holdOverridden" to "Lataus käynnistettiin suunnitelman ulkopuolella ja sen annetaan jatkua.",
            "status.stoppedByPerson" to "Pysäytit latauksen. Aurinko ei käynnistä sitä uudelleen ennen kuin auto kytketään uudelleen, painat Käynnistä nyt tai suunniteltu jakso alkaa.",
            "status.stoppedByPersonUntilStart" to "Pysäytit latauksen. Aurinko ei käynnistä sitä uudelleen ennen kuin painat Käynnistä nyt tai seuraava suunniteltu jakso alkaa.",
            "status.siteMeasurement.stale.other" to "{phases}: arvot ovat yli {seconds} s vanhoja.",
            "status.siteMeasurement.stale.one" to "{phases}: arvo on yli {seconds} s vanha.",
            "status.siteMeasurement.noValue.other" to "{phases}: ei arvoa{where}.",
            "status.siteMeasurement.noValue.one" to "{phases}: ei arvoa{where}.",
            "issue.duplicateCharger" to "{other} ja tämä latauslaite ovat sama fyysinen laite. Kaksi SpotNav-latauslaitetta yhdellä laitteella lähettää sille ristiriitaisia komentoja, joten säilytä vain yksi: poista toinen kohdasta Asetukset → Laitteet ja palvelut → SpotNav. SpotNav ei koskaan poista kumpaakaan puolestasi.",
            "status.startingUp" to "Käynnistyy…",
            "issue.needKept" to "Energiamittaria ei voi lukea: {kwh} kWh jäljellä sen viimeisimmän lukeman mukaan.",
            "issue.needFromSessions" to "Ei energiamittaria: {kwh} kWh jäljellä laturin tallennettujen latausten perusteella.",
            "status.needLimitedByRoom" to "Enintään {kwh} kWh: auto on lähes täynnä.",
            "status.chargingToVehicleLimit" to "Ladataan, kunnes auto lopettaa itse omaan latausrajaansa ({percent} %).",
            "issue.siteMeasurement" to "Kohteen mittausta ei voi käyttää juuri nyt.",
            "control.pausedUntil" to "Keskeytetty {time} asti.",
            "issue.chargerMissing" to "Valittua laturia ei voi käyttää: se on tuntematon, ei ladattu tai kyseessä on asema.",
            "issue.chargingWithoutPrices" to "Ladataan ilman julkaistuja hintoja, jotta määräaika pysyy.",
            "issue.error" to "Viimeisin laskenta epäonnistui.",
            "issue.estimated" to "Osa suunnitelmasta latautuu ilman julkaistuja hintoja.",
            "issue.incompleteSettings" to "Viimeistele asetukset: joitakin asetuksia puuttuu vielä. Avaa Asetukset.",
            "issue.loadBalancing" to "Kuormanhallinta ei ole käytettävissä tälle laturille.",
            "issue.planningUnavailable" to "Lataussuunnitelmaa ei voitu laskea käytettävissä olevilla tiedoilla juuri nyt.",
            "issue.priceDegraded" to "Hintatiedot ovat puutteellisia.",
            "issue.priceHorizon" to "Hinnat puuttuvat osasta suunnitteluikkunaa. Aseta lähtöaika.",
            "issue.priceInvalid" to "Hintatiedot ovat virheellisiä.",
            "issue.priceStale" to "Hinnat ovat vanhentuneita: viimeisin onnistunut haku on yhä käytössä.",
            "issue.priceUnavailable" to "Käyttökelpoisia hintatietoja ei ole juuri nyt.",
            "issue.solarUnavailable" to "Aurinkolataus ei ole käytettävissä: tämä kohde ei voi mitata aurinkoylijäämää.",
            "issue.targetSocUnknown" to "Lataustason tavoitetta ei voi suunnitella: ajoneuvon lataustaso tai akun kapasiteetti ei ole tiedossa. Avaa Suunnitelma valitaksesi anturin tai antaaksesi kapasiteetin.",
            "issue.targetUnverifiable" to "Tavoitetta ei voi tarkistaa juuri nyt.",
            "status.autoInstalled" to "Lataus on aikataulutettu klo {time} alkaen.",
            "status.autoPlanned" to "Suunniteltu klo {time} alkaen.",
            "status.buyingBeforePublication" to "Ostetaan {kwh} kWh nyt, loput kun hinnat on julkaistu.",
            "status.chargingNow" to "Ladataan nyt; aikataulun mukaan {time} asti.",
            "status.chargingNowOpen" to "Ladataan nyt.",
            "status.toppingOff" to "Ladataan, kunnes auto on täynnä (enintään klo {time} asti).",
            "status.toppingOffOpen" to "Ladataan, kunnes auto on täynnä.",
            "status.loadBalancingLimited" to "Aseman kuormanhallinta rajoittaa latausta juuri nyt.",
            "status.loadBalancingLimitedTo" to "Aseman kuormanhallinta rajoittaa latauksen {limit} A:iin.",
            "status.noPlan" to "Lataussuunnitelmaa ei voitu laskea juuri nyt.",
            "status.nothingToCharge" to "Ei mitään ladattavaa juuri nyt.",
            "status.pausedShort" to "Automaattinen lataus on keskeytetty.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "Uusi latausehdotus on valmis.",
            "status.scheduledNoTime" to "Lataus on aikataulutettu.",
            "status.targetAgeHours" to "{n} h",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Pysäytetty {soc} %:iin",
            "status.targetStoppedAge" to "Pysäytetty {soc} %:iin (lukema on {age} vanha)",
            "status.targetStoppedEstimate" to "Pysäytetty {soc} %:iin (arvio)",
            "status.targetStoppedEstimateAge" to "Pysäytetty {soc} %:iin (arvio, lukema on {age} vanha)",
            "status.targetStoppedNow" to "Pysäytetty {soc} %:iin (juuri äsken)",
            "status.waitingForPublication" to "Odotetaan huomisen hintoja (~{time}), suunnitellaan sen jälkeen.",
            "status.waitingForPublicationNoTime" to "Odotetaan huomisen hintoja, suunnitellaan sen jälkeen.",
            "status.waitingForTomorrow" to "Odotetaan huomisen hintoja.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh odotetaan auringosta",
            "strategy.status.hybrid.grid" to "Hybridi · {grid} kWh verkosta{window}",
            "strategy.status.hybrid.noForecast" to "Hybridi · ei ennustelähdettä — suunnittelee kuin Halvin",
            "strategy.status.hybrid.noPriceData" to "Hybridi · odottaa hintatietoja",
            "strategy.status.hybrid.satisfied" to "Hybridi · lataustarve on jo täytetty",
            "strategy.status.hybrid.unknown" to "Hybridi · suunnittelee",
            "strategy.status.solar.arming" to "Aurinko · ylijäämää löytyi, käynnistyy pian",
            "strategy.status.solar.charging" to "Aurinko · lataa {amps} A ylijäämästä",
            "strategy.status.solar.chargingUnknown" to "Aurinko · lataa ylijäämästä",
            "strategy.status.solar.disarming" to "Aurinko · ylijäämä vähenee, pysähtyy pian",
            "strategy.status.solar.noReadingStopped" to "Aurinko · pysäytetty, ei käyttökelpoista mittausta",
            "strategy.status.solar.noReadingWaiting" to "Aurinko · ei vielä käyttökelpoista mittausta",
            "strategy.status.solar.unknown" to "Aurinko · tila tuntematon",
            "strategy.status.solar.waitingForSun" to "Aurinko · odottaa aurinkoa",
            "strategy.status.solar.vehicleFull" to "Aurinko · auto on täynnä",
            "strategy.status.solar.carStopped" to "Aurinko · auto lopetti latauksen; yritetään uudelleen klo {time}",
            "strategy.status.solar.carStoppedNoTime" to "Aurinko · auto lopetti latauksen",
            "strategy.status.solar.noGridPower" to "Aurinko · verkon tehosta ei ole mittausta — aseta Verkon kokonaisteho kohdassa Laitoksen entiteetit",
            "strategy.status.solar.noGridPowerEntity" to "Aurinko · verkon kokonaisteholla ({entity}) ei ole tuoretta mittausta",
            "strategy.status.solar.batteryUnreadable" to "Aurinko · akun teholla ({entity}) ei ole tuoretta mittausta",
            "strategy.status.solar.chargerCurrentNotSet" to "Laturin omaa virtaa ei ole valittu — valitse se kohdassa Kohteen kytkentä (esim. Easee Current); siihen asti aurinko käynnistyy vain pienimmällä virralla.",
            "strategy.status.solar.chargerCurrentUnreadable" to "Laturin omalla virralla ({entity}) ei ole mittausta; siihen asti aurinko käynnistyy vain pienimmällä virralla.",
            "strategy.status.solar.siteIncomplete" to "Kohteen mittaus on puutteellinen ({phases}) — aurinko toimii vain verkon kokonaisteholla.",
            "status.meterUnavailable.inverter" to "Mittarin anturit eivät ole käytettävissä (invertteri voi olla valmiustilassa): {entities}.",
            "status.meterUnavailable.meter" to "Mittarin anturit eivät ole käytettävissä: {entities}.",
            "status.finishSetupArea" to "Viimeistele asetukset: valitse hinta-alue Asetuksissa.",
            "status.finishSetup" to "Viimeistele asetukset Asetuksissa: {fields}.",
            "status.settingsSuggested" to "Ehdotettu sijaintisi ja laturin perusteella – tarkista Asetukset.",
            "status.missing.area" to "hinta-alue",
            "status.missing.phases" to "vaiheet",
            "status.missing.amps" to "latausvirta",
            "status.missing.vehicle" to "ajoneuvo",
            "status.missing.target_percent" to "tavoitetaso",
        ),
    )

    /** The locales the app is translated into. */
    val LANGUAGES: List<String> = listOf("en", "sv", "da", "nb", "fi")

    /**
     * [key] in [language] (English for a language this table has none of), or `null` when there is
     * no wording.
     */
    fun text(language: String, key: String): String? {
        val table = if (language in CARD) language else "en"
        return CARD.getValue(table)[key] ?: APP_ONLY.getValue(table)[key]
    }
}
