package se.sensnology.spotnav.ha.dashboard

/**
 * The words of the status line, one table per locale, taken from the Home Assistant card's own
 * translations (`frontend/src/i18n`) so the app says the same thing in the same words.
 */
internal object HaStatusWording {
    /** The sentence each Home Assistant status code is worded with (`status.ts`' `STATUS_WORDING`). */
    val CODE_KEYS: Map<String, String> = mapOf(
        "charger_unavailable" to "issue.chargerMissing",
        "price_data_invalid" to "issue.priceInvalid",
        "price_data_unavailable" to "issue.priceUnavailable",
        "settings_incomplete" to "issue.incompleteSettings",
        "settings_suggested" to "status.settingsSuggested",
        "solar_unavailable" to "issue.solarUnavailable",
        "target_soc_unknown" to "issue.targetSocUnknown",
        "price_horizon_missing" to "issue.priceHorizon",
        "planning_unavailable" to "issue.planningUnavailable",
        "planning_error" to "issue.error",
        "paused" to "control.pausedUntil",
        "charging_now" to "status.chargingNow",
        "charging_without_prices" to "issue.chargingWithoutPrices",
        "waiting_for_publication" to "status.waitingForPublication",
        "buying_before_publication" to "status.buyingBeforePublication",
        "auto_planned" to "status.autoPlanned",
        "auto_installed" to "status.autoInstalled",
        "proposal_pending" to "status.proposalPending",
        "waiting_for_tomorrow" to "status.waitingForTomorrow",
        "no_plan" to "status.noPlan",
        "nothing_to_charge" to "status.nothingToCharge",
        "plan_energy" to "status.planEnergy",
        "plan_cost" to "status.planCost",
        "plan_distance" to "status.planDistance",
        "solar_charging" to "strategy.status.solar.charging",
        "solar_arming" to "strategy.status.solar.arming",
        "solar_disarming" to "strategy.status.solar.disarming",
        "solar_no_reading_stopped" to "strategy.status.solar.noReadingStopped",
        "solar_no_reading_waiting" to "strategy.status.solar.noReadingWaiting",
        "solar_waiting_for_sun" to "strategy.status.solar.waitingForSun",
        "solar_unknown" to "strategy.status.solar.unknown",
        "hybrid_grid" to "strategy.status.hybrid.grid",
        "hybrid_no_forecast" to "strategy.status.hybrid.noForecast",
        "hybrid_no_price_data" to "strategy.status.hybrid.noPriceData",
        "hybrid_satisfied" to "strategy.status.hybrid.satisfied",
        "hybrid_unknown" to "strategy.status.hybrid.unknown",
        "target_reached" to "status.targetStopped",
        "target_unverifiable" to "issue.targetUnverifiable",
        "price_data_stale" to "issue.priceStale",
        "price_data_degraded" to "issue.priceDegraded",
        "unpriced" to "issue.estimated",
        "load_balancing_limited" to "status.loadBalancingLimitedTo",
        "load_balancing_unavailable" to "issue.loadBalancing",
        "waiting_for_history" to "status.waitingForHistory",
        "held_by_charger" to "issue.heldByCharger",
        "charger_disabled" to "issue.chargerDisabled",
        "held_until_window" to "status.heldUntilWindow",
        "hold_overridden" to "issue.holdOverridden",
    )

    /** The extra keys a code's variants use (an absent fact, or no zone to write an instant in). */
    val VARIANT_KEYS: List<String> = listOf(
        "status.finishSetupArea",
        "status.finishSetup",
        "status.missing.area",
        "status.missing.phases",
        "status.missing.amps",
        "status.missing.vehicle",
        "status.missing.target_percent",
        "control.pausedIndefinitely",
        "status.pausedShort",
        "status.targetStoppedAge",
        "status.targetStoppedNow",
        "status.targetStoppedEstimate",
        "status.targetStoppedEstimateAge",
        "status.targetAgeMinutes",
        "status.targetAgeHours",
        "status.chargingNowOpen",
        "status.scheduledNoTime",
        "status.waitingForPublicationNoTime",
        "status.loadBalancingLimited",
        "status.waitingForHistoryNoDetail",
        "strategy.status.solar.chargingUnknown",
        "strategy.status.hybrid.creditSuffix",
    )

    /** The app's own additions: a status this app version cannot word, and the age of a kept one. */
    const val UNKNOWN_CODE = "app.status.unknown"
    const val STALE_SUFFIX = "app.status.staleSuffix"

    private val APP_ONLY: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(UNKNOWN_CODE to "Charging status: see Home Assistant.", STALE_SUFFIX to "updated {age} ago"),
        "sv" to mapOf(UNKNOWN_CODE to "Laddstatus: se Home Assistant.", STALE_SUFFIX to "uppdaterad för {age} sedan"),
        "da" to mapOf(UNKNOWN_CODE to "Ladestatus: se Home Assistant.", STALE_SUFFIX to "opdateret for {age} siden"),
        "nb" to mapOf(UNKNOWN_CODE to "Ladestatus: se Home Assistant.", STALE_SUFFIX to "oppdatert for {age} siden"),
        "fi" to mapOf(UNKNOWN_CODE to "Latauksen tila: katso Home Assistant.", STALE_SUFFIX to "päivitetty {age} sitten"),
    )

    private val CARD: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "control.pausedIndefinitely" to "Paused until you resume.",
            "status.heldUntilWindow" to "Charging waits for the planned start at {time}.",
            "status.waitingForHistory" to "Waiting: {weekday} were {percent} % cheaper the last {weeks} weeks.",
            "status.waitingForHistoryNoDetail" to "Waiting for hours that usually cost less, will plan then.",
            "issue.heldByCharger" to "The charger's own schedule or load balancing is holding the charge, so it has not started.",
            "issue.chargerDisabled" to "The charger's own enable switch is off, so it cannot start. Turn it on in the charger's settings.",
            "issue.holdOverridden" to "Charging was started outside the plan and is allowed to continue.",
            "control.pausedUntil" to "Paused until {time}.",
            "issue.chargerMissing" to "The configured charger is not usable: it is unknown, unloaded or a site.",
            "issue.chargingWithoutPrices" to "Charging without published prices to keep the deadline.",
            "issue.error" to "The last calculation failed.",
            "issue.estimated" to "Part of the plan charges without published prices.",
            "issue.incompleteSettings" to "Finish setting up: some settings are still missing. Open Settings.",
            "issue.loadBalancing" to "Load balancing is not available for this charger.",
            "issue.planningUnavailable" to "No charging plan could be calculated with the data available right now.",
            "issue.priceDegraded" to "The price data is incomplete.",
            "issue.priceHorizon" to "Prices are missing for part of the required planning window. Set a deadline.",
            "issue.priceInvalid" to "The price data is invalid.",
            "issue.priceStale" to "The prices are stale: the last successful fetch is still being used.",
            "issue.priceUnavailable" to "No usable price data is available right now.",
            "issue.solarUnavailable" to "Solar charging is not available: this site cannot measure solar surplus.",
            "issue.targetSocUnknown" to "The target charge level cannot be planned: the vehicle's charge level or battery capacity is not known. Open Plan to choose a sensor or enter the capacity.",
            "issue.targetUnverifiable" to "The target can't be checked right now.",
            "status.autoInstalled" to "Charging is scheduled from {time}.",
            "status.autoPlanned" to "Planned from {time}.",
            "status.buyingBeforePublication" to "Buying {kwh} kWh now, the rest when the prices are published.",
            "status.chargingNow" to "Charging now; scheduled until {time}.",
            "status.chargingNowOpen" to "Charging now.",
            "status.loadBalancingLimited" to "Charging is limited by the site's load balancing right now.",
            "status.loadBalancingLimitedTo" to "Charging is limited to {limit} A by the site's load balancing.",
            "status.noPlan" to "No charging plan could be calculated right now.",
            "status.nothingToCharge" to "Nothing to charge right now.",
            "status.pausedShort" to "Automatic charging is paused.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "A new charging proposal is ready.",
            "status.scheduledNoTime" to "Charging is scheduled.",
            "status.targetAgeHours" to "{n} h",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Stopped at {soc} %",
            "status.targetStoppedAge" to "Stopped at {soc} % (reading {age} old)",
            "status.targetStoppedEstimate" to "Stopped at {soc} % (estimated)",
            "status.targetStoppedEstimateAge" to "Stopped at {soc} % (estimated, reading {age} old)",
            "status.targetStoppedNow" to "Stopped at {soc} % (just now)",
            "status.waitingForPublication" to "Waiting for tomorrow's prices (~{time}), will plan then.",
            "status.waitingForPublicationNoTime" to "Waiting for tomorrow's prices, will plan then.",
            "status.waitingForTomorrow" to "Waiting for tomorrow's prices.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh expected from sun",
            "strategy.status.hybrid.grid" to "Hybrid · {grid} kWh from grid{window}",
            "strategy.status.hybrid.noForecast" to "Hybrid · no forecast source — planning like Cheapest",
            "strategy.status.hybrid.noPriceData" to "Hybrid · waiting for price data",
            "strategy.status.hybrid.satisfied" to "Hybrid · charging need already met",
            "strategy.status.hybrid.unknown" to "Hybrid · planning",
            "strategy.status.solar.arming" to "Solar · surplus found, starting soon",
            "strategy.status.solar.charging" to "Solar · charging {amps} A from surplus",
            "strategy.status.solar.chargingUnknown" to "Solar · charging from surplus",
            "strategy.status.solar.disarming" to "Solar · surplus fading, stopping soon",
            "strategy.status.solar.noReadingStopped" to "Solar · stopped, no usable reading",
            "strategy.status.solar.noReadingWaiting" to "Solar · no usable reading yet",
            "strategy.status.solar.unknown" to "Solar · status unknown",
            "strategy.status.solar.waitingForSun" to "Solar · waiting for sun",
            "status.finishSetupArea" to "Finish setting up: choose a price area in Settings.",
            "status.finishSetup" to "Finish setting up in Settings: {fields}.",
            "status.settingsSuggested" to "Suggested from your location and charger – check Settings.",
            "status.missing.area" to "price area",
            "status.missing.phases" to "phases",
            "status.missing.amps" to "charging current",
            "status.missing.vehicle" to "vehicle",
            "status.missing.target_percent" to "target level",
        ),
        "sv" to mapOf(
            "control.pausedIndefinitely" to "Pausad tills du återupptar.",
            "status.heldUntilWindow" to "Laddningen väntar till planerad start kl. {time}.",
            "status.waitingForHistory" to "Väntar: {weekday} har varit {percent} % billigare de senaste {weeks} veckorna.",
            "status.waitingForHistoryNoDetail" to "Väntar på timmar som brukar vara billigare, planerar då.",
            "issue.heldByCharger" to "Laddarens eget schema eller lastbalansering håller tillbaka laddningen, så den har inte startat.",
            "issue.chargerDisabled" to "Laddarens egen aktiveringsbrytare är av, så den kan inte starta. Slå på den i laddarens inställningar.",
            "issue.holdOverridden" to "Laddningen startades utanför planen och får fortsätta.",
            "control.pausedUntil" to "Pausad till {time}.",
            "issue.chargerMissing" to "Den valda laddaren går inte att använda: den är okänd, inte laddad eller en anläggning.",
            "issue.chargingWithoutPrices" to "Laddar utan publicerade priser för att hålla sluttiden.",
            "issue.error" to "Den senaste beräkningen misslyckades.",
            "issue.estimated" to "En del av planen laddar utan publicerade priser.",
            "issue.incompleteSettings" to "Slutför inställningen: några inställningar saknas fortfarande. Öppna Inställningar.",
            "issue.loadBalancing" to "Lastbalansering är inte tillgänglig för den här laddaren.",
            "issue.planningUnavailable" to "Ingen laddplan kunde beräknas med de uppgifter som finns just nu.",
            "issue.priceDegraded" to "Prisunderlaget är ofullständigt.",
            "issue.priceHorizon" to "Priser saknas för en del av planeringsperioden. Ange en avresetid.",
            "issue.priceInvalid" to "Prisuppgifterna är ogiltiga.",
            "issue.priceStale" to "Priserna är inaktuella: den senaste lyckade hämtningen används fortfarande.",
            "issue.priceUnavailable" to "Inga användbara prisuppgifter finns just nu.",
            "issue.solarUnavailable" to "Solladdning är inte tillgänglig: anläggningen kan inte mäta solöverskott.",
            "issue.targetSocUnknown" to "Målnivån kan inte planeras: fordonets laddnivå eller batterikapacitet är okänd. Öppna Plan för att välja sensor eller ange kapaciteten.",
            "issue.targetUnverifiable" to "Målet kan inte kontrolleras just nu.",
            "status.autoInstalled" to "Laddning är schemalagd från {time}.",
            "status.autoPlanned" to "Planerat från {time}.",
            "status.buyingBeforePublication" to "Köper {kwh} kWh nu, resten när priserna publiceras.",
            "status.chargingNow" to "Laddar nu; schemalagd till {time}.",
            "status.chargingNowOpen" to "Laddar nu.",
            "status.loadBalancingLimited" to "Laddningen begränsas av anläggningens lastbalansering just nu.",
            "status.loadBalancingLimitedTo" to "Laddningen begränsas till {limit} A av anläggningens lastbalansering.",
            "status.noPlan" to "Ingen laddplan kunde beräknas just nu.",
            "status.nothingToCharge" to "Inget att ladda just nu.",
            "status.pausedShort" to "Automatisk laddning är pausad.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "Ett nytt laddförslag är klart.",
            "status.scheduledNoTime" to "Laddning är schemalagd.",
            "status.targetAgeHours" to "{n} h",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Stoppad vid {soc} %",
            "status.targetStoppedAge" to "Stoppad vid {soc} % (avläsningen {age} gammal)",
            "status.targetStoppedEstimate" to "Stoppad vid {soc} % (uppskattat)",
            "status.targetStoppedEstimateAge" to "Stoppad vid {soc} % (uppskattat, avläsningen {age} gammal)",
            "status.targetStoppedNow" to "Stoppad vid {soc} % (nyss)",
            "status.waitingForPublication" to "Väntar på morgondagens priser (~{time}), planerar då.",
            "status.waitingForPublicationNoTime" to "Väntar på morgondagens priser, planerar då.",
            "status.waitingForTomorrow" to "Väntar på morgondagens priser.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh väntas från solen",
            "strategy.status.hybrid.grid" to "Hybrid · {grid} kWh från elnätet{window}",
            "strategy.status.hybrid.noForecast" to "Hybrid · ingen prognoskälla — planerar som Billigast",
            "strategy.status.hybrid.noPriceData" to "Hybrid · väntar på prisuppgifter",
            "strategy.status.hybrid.satisfied" to "Hybrid · laddbehovet är redan uppfyllt",
            "strategy.status.hybrid.unknown" to "Hybrid · planerar",
            "strategy.status.solar.arming" to "Sol · överskott hittat, startar snart",
            "strategy.status.solar.charging" to "Sol · laddar med {amps} A från överskott",
            "strategy.status.solar.chargingUnknown" to "Sol · laddar från överskott",
            "strategy.status.solar.disarming" to "Sol · överskottet minskar, stoppar snart",
            "strategy.status.solar.noReadingStopped" to "Sol · stoppad, ingen användbar mätning",
            "strategy.status.solar.noReadingWaiting" to "Sol · ingen användbar mätning ännu",
            "strategy.status.solar.unknown" to "Sol · status okänd",
            "strategy.status.solar.waitingForSun" to "Sol · väntar på sol",
            "status.finishSetupArea" to "Slutför inställningen: välj ett prisområde i Inställningar.",
            "status.finishSetup" to "Slutför inställningen i Inställningar: {fields}.",
            "status.settingsSuggested" to "Förslag utifrån din plats och laddare – kontrollera Inställningar.",
            "status.missing.area" to "prisområde",
            "status.missing.phases" to "faser",
            "status.missing.amps" to "laddström",
            "status.missing.vehicle" to "fordon",
            "status.missing.target_percent" to "målnivå",
        ),
        "da" to mapOf(
            "control.pausedIndefinitely" to "Sat på pause, indtil du genoptager.",
            "status.heldUntilWindow" to "Opladningen venter til den planlagte start kl. {time}.",
            "status.waitingForHistory" to "Venter: {weekday} har været {percent} % billigere de seneste {weeks} uger.",
            "status.waitingForHistoryNoDetail" to "Venter på timer, der plejer at være billigere, planlægger derefter.",
            "issue.heldByCharger" to "Laderens eget skema eller lastbalancering holder opladningen tilbage, så den er ikke startet.",
            "issue.chargerDisabled" to "Laderens egen aktiveringskontakt er slået fra, så den kan ikke starte. Slå den til i laderens indstillinger.",
            "issue.holdOverridden" to "Opladningen blev startet uden for planen og må fortsætte.",
            "control.pausedUntil" to "Sat på pause til {time}.",
            "issue.chargerMissing" to "Den valgte lader kan ikke bruges: den er ukendt, ikke indlæst eller et anlæg.",
            "issue.chargingWithoutPrices" to "Lader uden offentliggjorte priser for at overholde sluttidspunktet.",
            "issue.error" to "Den seneste beregning mislykkedes.",
            "issue.estimated" to "En del af planen lader uden offentliggjorte priser.",
            "issue.incompleteSettings" to "Færdiggør opsætningen: nogle indstillinger mangler stadig. Åbn Indstillinger.",
            "issue.loadBalancing" to "Lastbalancering er ikke tilgængelig for denne lader.",
            "issue.planningUnavailable" to "Der kunne ikke beregnes en ladeplan med de data, der er tilgængelige lige nu.",
            "issue.priceDegraded" to "Prisdata er ufuldstændige.",
            "issue.priceHorizon" to "Priser mangler for en del af planlægningsvinduet. Angiv et afrejsetidspunkt.",
            "issue.priceInvalid" to "Prisdataene er ugyldige.",
            "issue.priceStale" to "Priserne er forældede: den seneste vellykkede hentning bruges stadig.",
            "issue.priceUnavailable" to "Der er ingen brugbare prisdata lige nu.",
            "issue.solarUnavailable" to "Soloplading er ikke tilgængelig: dette anlæg kan ikke måle soloverskud.",
            "issue.targetSocUnknown" to "Ladetilstandsmålet kan ikke planlægges: bilens ladetilstand eller batterikapacitet er ukendt. Åbn Plan for at vælge en sensor eller angive kapaciteten.",
            "issue.targetUnverifiable" to "Målet kan ikke kontrolleres lige nu.",
            "status.autoInstalled" to "Opladning er planlagt fra {time}.",
            "status.autoPlanned" to "Planlagt fra {time}.",
            "status.buyingBeforePublication" to "Køber {kwh} kWh nu, resten når priserne er offentliggjort.",
            "status.chargingNow" to "Lader nu; planlagt til {time}.",
            "status.chargingNowOpen" to "Lader nu.",
            "status.loadBalancingLimited" to "Opladningen begrænses af anlæggets lastbalancering lige nu.",
            "status.loadBalancingLimitedTo" to "Opladningen begrænses til {limit} A af anlæggets lastbalancering.",
            "status.noPlan" to "Der kunne ikke beregnes en ladeplan lige nu.",
            "status.nothingToCharge" to "Der er intet at lade lige nu.",
            "status.pausedShort" to "Automatisk opladning er sat på pause.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "Et nyt opladningsforslag er klar.",
            "status.scheduledNoTime" to "Opladning er planlagt.",
            "status.targetAgeHours" to "{n} t",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Stoppet ved {soc} %",
            "status.targetStoppedAge" to "Stoppet ved {soc} % (aflæsningen er {age} gammel)",
            "status.targetStoppedEstimate" to "Stoppet ved {soc} % (anslået)",
            "status.targetStoppedEstimateAge" to "Stoppet ved {soc} % (anslået, aflæsningen er {age} gammel)",
            "status.targetStoppedNow" to "Stoppet ved {soc} % (lige nu)",
            "status.waitingForPublication" to "Venter på morgendagens priser (~{time}), planlægger derefter.",
            "status.waitingForPublicationNoTime" to "Venter på morgendagens priser, planlægger derefter.",
            "status.waitingForTomorrow" to "Venter på morgendagens priser.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh forventes fra solen",
            "strategy.status.hybrid.grid" to "Hybrid · {grid} kWh fra elnettet{window}",
            "strategy.status.hybrid.noForecast" to "Hybrid · ingen prognosekilde — planlægger som Billigst",
            "strategy.status.hybrid.noPriceData" to "Hybrid · venter på prisdata",
            "strategy.status.hybrid.satisfied" to "Hybrid · ladebehovet er allerede opfyldt",
            "strategy.status.hybrid.unknown" to "Hybrid · planlægger",
            "strategy.status.solar.arming" to "Sol · overskud fundet, starter snart",
            "strategy.status.solar.charging" to "Sol · lader med {amps} A fra overskud",
            "strategy.status.solar.chargingUnknown" to "Sol · lader fra overskud",
            "strategy.status.solar.disarming" to "Sol · overskuddet aftager, stopper snart",
            "strategy.status.solar.noReadingStopped" to "Sol · stoppet, ingen brugbar måling",
            "strategy.status.solar.noReadingWaiting" to "Sol · ingen brugbar måling endnu",
            "strategy.status.solar.unknown" to "Sol · status ukendt",
            "strategy.status.solar.waitingForSun" to "Sol · venter på sol",
            "status.finishSetupArea" to "Færdiggør opsætningen: vælg et prisområde i Indstillinger.",
            "status.finishSetup" to "Færdiggør opsætningen i Indstillinger: {fields}.",
            "status.settingsSuggested" to "Foreslået ud fra din placering og lader – tjek Indstillinger.",
            "status.missing.area" to "prisområde",
            "status.missing.phases" to "faser",
            "status.missing.amps" to "ladestrøm",
            "status.missing.vehicle" to "køretøj",
            "status.missing.target_percent" to "målniveau",
        ),
        "nb" to mapOf(
            "control.pausedIndefinitely" to "Pauset til du gjenopptar.",
            "status.heldUntilWindow" to "Ladingen venter til planlagt start kl. {time}.",
            "status.waitingForHistory" to "Venter: {weekday} har vært {percent} % billigere de siste {weeks} ukene.",
            "status.waitingForHistoryNoDetail" to "Venter på timer som pleier å være billigere, planlegger da.",
            "issue.heldByCharger" to "Laderens egen timeplan eller lastbalansering holder tilbake ladingen, så den har ikke startet.",
            "issue.chargerDisabled" to "Laderens egen aktiveringsbryter er av, så den kan ikke starte. Slå den på i laderens innstillinger.",
            "issue.holdOverridden" to "Ladingen ble startet utenfor planen og får fortsette.",
            "control.pausedUntil" to "Pauset til {time}.",
            "issue.chargerMissing" to "Den valgte laderen kan ikke brukes: den er ukjent, ikke lastet eller et anlegg.",
            "issue.chargingWithoutPrices" to "Lader uten publiserte priser for å holde sluttiden.",
            "issue.error" to "Den siste beregningen mislyktes.",
            "issue.estimated" to "En del av planen lader uten publiserte priser.",
            "issue.incompleteSettings" to "Fullfør oppsettet: noen innstillinger mangler fortsatt. Åpne Innstillinger.",
            "issue.loadBalancing" to "Lastbalansering er ikke tilgjengelig for denne laderen.",
            "issue.planningUnavailable" to "Ingen ladeplan kunne beregnes med dataene som finnes akkurat nå.",
            "issue.priceDegraded" to "Prisdataene er ufullstendige.",
            "issue.priceHorizon" to "Priser mangler for en del av planleggingsvinduet. Angi et avreisetidspunkt.",
            "issue.priceInvalid" to "Prisdataene er ugyldige.",
            "issue.priceStale" to "Prisene er utdaterte: den siste vellykkede hentingen brukes fortsatt.",
            "issue.priceUnavailable" to "Ingen brukbare prisdata finnes akkurat nå.",
            "issue.solarUnavailable" to "Sollading er ikke tilgjengelig: dette anlegget kan ikke måle soloverskudd.",
            "issue.targetSocUnknown" to "Ladenivåmålet kan ikke planlegges: bilens ladenivå eller batterikapasitet er ukjent. Åpne Plan for å velge sensor eller oppgi kapasiteten.",
            "issue.targetUnverifiable" to "Målet kan ikke kontrolleres akkurat nå.",
            "status.autoInstalled" to "Lading er planlagt fra {time}.",
            "status.autoPlanned" to "Planlagt fra {time}.",
            "status.buyingBeforePublication" to "Kjøper {kwh} kWh nå, resten når prisene er publisert.",
            "status.chargingNow" to "Lader nå; planlagt til {time}.",
            "status.chargingNowOpen" to "Lader nå.",
            "status.loadBalancingLimited" to "Ladingen begrenses av anleggets lastbalansering akkurat nå.",
            "status.loadBalancingLimitedTo" to "Ladingen begrenses til {limit} A av anleggets lastbalansering.",
            "status.noPlan" to "Ingen ladeplan kunne beregnes akkurat nå.",
            "status.nothingToCharge" to "Ingenting å lade akkurat nå.",
            "status.pausedShort" to "Automatisk lading er pauset.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "Et nytt ladeforslag er klart.",
            "status.scheduledNoTime" to "Lading er planlagt.",
            "status.targetAgeHours" to "{n} t",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Stoppet ved {soc} %",
            "status.targetStoppedAge" to "Stoppet ved {soc} % (avlesningen er {age} gammel)",
            "status.targetStoppedEstimate" to "Stoppet ved {soc} % (anslått)",
            "status.targetStoppedEstimateAge" to "Stoppet ved {soc} % (anslått, avlesningen er {age} gammel)",
            "status.targetStoppedNow" to "Stoppet ved {soc} % (akkurat nå)",
            "status.waitingForPublication" to "Venter på morgendagens priser (~{time}), planlegger da.",
            "status.waitingForPublicationNoTime" to "Venter på morgendagens priser, planlegger da.",
            "status.waitingForTomorrow" to "Venter på morgendagens priser.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh forventes fra solen",
            "strategy.status.hybrid.grid" to "Hybrid · {grid} kWh fra strømnettet{window}",
            "strategy.status.hybrid.noForecast" to "Hybrid · ingen prognosekilde — planlegger som Billigst",
            "strategy.status.hybrid.noPriceData" to "Hybrid · venter på prisdata",
            "strategy.status.hybrid.satisfied" to "Hybrid · ladebehovet er allerede dekket",
            "strategy.status.hybrid.unknown" to "Hybrid · planlegger",
            "strategy.status.solar.arming" to "Sol · overskudd funnet, starter snart",
            "strategy.status.solar.charging" to "Sol · lader med {amps} A fra overskudd",
            "strategy.status.solar.chargingUnknown" to "Sol · lader fra overskudd",
            "strategy.status.solar.disarming" to "Sol · overskuddet avtar, stopper snart",
            "strategy.status.solar.noReadingStopped" to "Sol · stoppet, ingen brukbar måling",
            "strategy.status.solar.noReadingWaiting" to "Sol · ingen brukbar måling ennå",
            "strategy.status.solar.unknown" to "Sol · status ukjent",
            "strategy.status.solar.waitingForSun" to "Sol · venter på sol",
            "status.finishSetupArea" to "Fullfør oppsettet: velg et prisområde i Innstillinger.",
            "status.finishSetup" to "Fullfør oppsettet i Innstillinger: {fields}.",
            "status.settingsSuggested" to "Foreslått ut fra plassering og lader – sjekk Innstillinger.",
            "status.missing.area" to "prisområde",
            "status.missing.phases" to "faser",
            "status.missing.amps" to "ladestrøm",
            "status.missing.vehicle" to "kjøretøy",
            "status.missing.target_percent" to "målnivå",
        ),
        "fi" to mapOf(
            "control.pausedIndefinitely" to "Keskeytetty, kunnes jatkat.",
            "status.heldUntilWindow" to "Lataus odottaa suunniteltua alkamisaikaa klo {time}.",
            "status.waitingForHistory" to "Odotetaan: {weekday} on ollut {percent} % halvempaa viimeisten {weeks} viikon aikana.",
            "status.waitingForHistoryNoDetail" to "Odotetaan tunteja, jotka ovat yleensä halvempia, suunnitellaan sen jälkeen.",
            "issue.heldByCharger" to "Laturin oma aikataulu tai kuormanhallinta pidättää latausta, joten se ei ole alkanut.",
            "issue.chargerDisabled" to "Laturin oma käyttöönottokytkin on pois päältä, joten lataus ei voi alkaa. Kytke se päälle laturin asetuksista.",
            "issue.holdOverridden" to "Lataus käynnistettiin suunnitelman ulkopuolella ja sen annetaan jatkua.",
            "control.pausedUntil" to "Keskeytetty {time} asti.",
            "issue.chargerMissing" to "Valittua laturia ei voi käyttää: se on tuntematon, ei ladattu tai kyseessä on asema.",
            "issue.chargingWithoutPrices" to "Ladataan ilman julkaistuja hintoja, jotta määräaika pysyy.",
            "issue.error" to "Viimeisin laskenta epäonnistui.",
            "issue.estimated" to "Osa suunnitelmasta latautuu ilman julkaistuja hintoja.",
            "issue.incompleteSettings" to "Viimeistele asetukset: joitakin asetuksia puuttuu vielä. Avaa Asetukset.",
            "issue.loadBalancing" to "Kuormanhallinta ei ole käytettävissä tälle laturille.",
            "issue.planningUnavailable" to "Lataussuunnitelmaa ei voitu laskea käytettävissä olevilla tiedoilla juuri nyt.",
            "issue.priceDegraded" to "Hintatiedot ovat puutteellisia.",
            "issue.priceHorizon" to "Hinnat puuttuvat osasta suunnitteluikkunaa. Aseta lähtöaika.",
            "issue.priceInvalid" to "Hintatiedot ovat virheellisiä.",
            "issue.priceStale" to "Hinnat ovat vanhentuneita: viimeisin onnistunut haku on yhä käytössä.",
            "issue.priceUnavailable" to "Käyttökelpoisia hintatietoja ei ole juuri nyt.",
            "issue.solarUnavailable" to "Aurinkolataus ei ole käytettävissä: tämä kohde ei voi mitata aurinkoylijäämää.",
            "issue.targetSocUnknown" to "Lataustason tavoitetta ei voi suunnitella: ajoneuvon lataustaso tai akun kapasiteetti ei ole tiedossa. Avaa Suunnitelma valitaksesi anturin tai antaaksesi kapasiteetin.",
            "issue.targetUnverifiable" to "Tavoitetta ei voi tarkistaa juuri nyt.",
            "status.autoInstalled" to "Lataus on aikataulutettu klo {time} alkaen.",
            "status.autoPlanned" to "Suunniteltu klo {time} alkaen.",
            "status.buyingBeforePublication" to "Ostetaan {kwh} kWh nyt, loput kun hinnat on julkaistu.",
            "status.chargingNow" to "Ladataan nyt; aikataulun mukaan {time} asti.",
            "status.chargingNowOpen" to "Ladataan nyt.",
            "status.loadBalancingLimited" to "Aseman kuormanhallinta rajoittaa latausta juuri nyt.",
            "status.loadBalancingLimitedTo" to "Aseman kuormanhallinta rajoittaa latauksen {limit} A:iin.",
            "status.noPlan" to "Lataussuunnitelmaa ei voitu laskea juuri nyt.",
            "status.nothingToCharge" to "Ei mitään ladattavaa juuri nyt.",
            "status.pausedShort" to "Automaattinen lataus on keskeytetty.",
            "status.planCost" to "{cost}",
            "status.planDistance" to "{distance}",
            "status.planEnergy" to "{kwh} kWh",
            "status.proposalPending" to "Uusi latausehdotus on valmis.",
            "status.scheduledNoTime" to "Lataus on aikataulutettu.",
            "status.targetAgeHours" to "{n} h",
            "status.targetAgeMinutes" to "{n} min",
            "status.targetStopped" to "Pysäytetty {soc} %:iin",
            "status.targetStoppedAge" to "Pysäytetty {soc} %:iin (lukema on {age} vanha)",
            "status.targetStoppedEstimate" to "Pysäytetty {soc} %:iin (arvio)",
            "status.targetStoppedEstimateAge" to "Pysäytetty {soc} %:iin (arvio, lukema on {age} vanha)",
            "status.targetStoppedNow" to "Pysäytetty {soc} %:iin (juuri äsken)",
            "status.waitingForPublication" to "Odotetaan huomisen hintoja (~{time}), suunnitellaan sen jälkeen.",
            "status.waitingForPublicationNoTime" to "Odotetaan huomisen hintoja, suunnitellaan sen jälkeen.",
            "status.waitingForTomorrow" to "Odotetaan huomisen hintoja.",
            "strategy.status.hybrid.creditSuffix" to ", {credit} kWh odotetaan auringosta",
            "strategy.status.hybrid.grid" to "Hybridi · {grid} kWh verkosta{window}",
            "strategy.status.hybrid.noForecast" to "Hybridi · ei ennustelähdettä — suunnittelee kuin Halvin",
            "strategy.status.hybrid.noPriceData" to "Hybridi · odottaa hintatietoja",
            "strategy.status.hybrid.satisfied" to "Hybridi · lataustarve on jo täytetty",
            "strategy.status.hybrid.unknown" to "Hybridi · suunnittelee",
            "strategy.status.solar.arming" to "Aurinko · ylijäämää löytyi, käynnistyy pian",
            "strategy.status.solar.charging" to "Aurinko · lataa {amps} A ylijäämästä",
            "strategy.status.solar.chargingUnknown" to "Aurinko · lataa ylijäämästä",
            "strategy.status.solar.disarming" to "Aurinko · ylijäämä vähenee, pysähtyy pian",
            "strategy.status.solar.noReadingStopped" to "Aurinko · pysäytetty, ei käyttökelpoista mittausta",
            "strategy.status.solar.noReadingWaiting" to "Aurinko · ei vielä käyttökelpoista mittausta",
            "strategy.status.solar.unknown" to "Aurinko · tila tuntematon",
            "strategy.status.solar.waitingForSun" to "Aurinko · odottaa aurinkoa",
            "status.finishSetupArea" to "Viimeistele asetukset: valitse hinta-alue Asetuksissa.",
            "status.finishSetup" to "Viimeistele asetukset Asetuksissa: {fields}.",
            "status.settingsSuggested" to "Ehdotettu sijaintisi ja laturin perusteella – tarkista Asetukset.",
            "status.missing.area" to "hinta-alue",
            "status.missing.phases" to "vaiheet",
            "status.missing.amps" to "latausvirta",
            "status.missing.vehicle" to "ajoneuvo",
            "status.missing.target_percent" to "tavoitetaso",
        ),
    )

    /** The locales the app is translated into. */
    val LANGUAGES: List<String> = listOf("en", "sv", "da", "nb", "fi")

    /**
     * [key] in [language] (English for a language this table has none of), or `null` when there is
     * no wording.
     */
    fun text(language: String, key: String): String? {
        val table = if (language in CARD) language else "en"
        return CARD.getValue(table)[key] ?: APP_ONLY.getValue(table)[key]
    }
}
